name: build_image
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      -  name: check code 
         uses: actions/checkout@v2


# build and Push
- uses: azure/docker-login@v2
  with:
    login-server: azhub.azurecr.io
    username: ${{ secrets.REGISTRY_USERNAME }}
    password: ${{ secrets.REGISTRY_PASSWORD }}

- run: |
    docker build . -t azhub.azurecr.io/appjsv:${{ github.sha }}
    docker push azhub.azurecr.io/appjsv:${{ github.sha }}